[project]
name = "gpx-project"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "gpxpy",
    "geopy",
    "tabula-py",
    "pandas",
    "python-dotenv",
]

[project.optional-dependencies]
test = [
    "pytest",
]